FILES = $(wildcard *.adoc)
NEWFILE = combined.adoc

default: program

program: $(NEWFILE)
	asciidoctor $(NEWFILE) -o $(NEWFILE:.adoc=.html)
	asciidoctor-pdf $(NEWFILE) -o $(NEWFILE:.adoc=.html)

$(NEWFILE): $(FILES)
	cat $(FILES) > $(NEWFILE)